import type { StudentFullRow } from "@/server/services/student-registry";

// Header text matches the original SY intake spreadsheet, in the same order.
export const EXPORT_COLUMNS: { header: string; key: keyof StudentFullRow; width?: number }[] = [
  { header: "No.", key: "intakeNo", width: 8 },
  { header: "Date of Intake Interview", key: "dateOfIntakeInterview", width: 20 },
  { header: "Child Code", key: "childCode", width: 20 },
  { header: "Batch Number", key: "batchNumber", width: 12 },
  { header: "Province", key: "province", width: 18 },
  { header: "City/ Municipality", key: "city", width: 18 },
  { header: "*Barangay", key: "barangay", width: 18 },
  { header: "*Sitio/ Phase", key: "sitioPhase", width: 16 },
  { header: "*Complete Address", key: "completeAddress", width: 28 },
  { header: "*Child's Surname", key: "surname", width: 16 },
  { header: "*Child's First Name", key: "firstName", width: 16 },
  { header: "*Middle Initial", key: "middleInitial", width: 10 },
  { header: "* Sex/ Gender", key: "sex", width: 10 },
  { header: "*Date of Birth", key: "dateOfBirth", width: 14 },
  { header: "*Age", key: "age", width: 8 },
  { header: "*Grade/ Year Level", key: "gradeLevel", width: 14 },
  { header: " Track for Senior High", key: "shsTrack", width: 16 },
  { header: "Course in College", key: "courseInCollege", width: 18 },
  { header: "*Name of School", key: "schoolName", width: 24 },
  { header: "*Child's Classification upon Admission", key: "classification", width: 24 },
  { header: "Reason for dropping out", key: "dropoutReason", width: 20 },
  { header: "Reason for dropping out: Others", key: "dropoutReasonOther", width: 20 },
  { header: "Children in Need of Special Protection ( CNSP Cluster)", key: "cnspCluster", width: 24 },
  { header: "Education Status", key: "educationStatus", width: 16 },
  { header: "HH Head: Surname", key: "hhHeadSurname", width: 16 },
  { header: "HH Head: First Name", key: "hhHeadFirstName", width: 16 },
  { header: "HH Head: Surname ( Mother)", key: "hhHeadSurnameMother", width: 16 },
  { header: "HH Head: First Name ( Mother)", key: "hhHeadFirstNameMother", width: 16 },
  { header: "Occupation of HH Head", key: "occupationOfHhHead", width: 20 },
  { header: "*Family Per Capita Income", key: "familyPerCapitaIncome", width: 20 },
  { header: "HC: House Ownership", key: "houseOwnership", width: 18 },
  { header: "HC: House Ownership: If others, specify", key: "houseOwnershipOther", width: 20 },
  { header: "Size of Dwelling", key: "sizeOfDwelling", width: 14 },
  { header: "Materials", key: "materials", width: 16 },
  { header: "Materials: If others, specify", key: "materialsOther", width: 18 },
  { header: "Water Supply", key: "waterSupply", width: 16 },
  { header: "Water Supply: If others, specify", key: "waterSupplyOther", width: 18 },
  { header: "Lighting Facilities", key: "lightingFacility", width: 16 },
  { header: "Lighting Facilities: If others, specify", key: "lightingFacilityOther", width: 18 },
  { header: "Toilet Facility", key: "toiletFacility", width: 16 },
  { header: "Toilet Facility: If others, specify", key: "toiletFacilityOther", width: 18 },
  { header: "Furniture/s", key: "furnitures", width: 16 },
  { header: "Presently served by welfare agency", key: "presentlyServedByWelfareAgency", width: 18 },
  { header: "Name of  Welfare Agency", key: "welfareAgencyName", width: 22 },
  { header: "Type of service Availed", key: "typeOfServiceAvailed", width: 20 },
  { header: "Membership in any organization", key: "isOrganizationMember", width: 16 },
  { header: "Type of Organization", key: "organizationType", width: 18 },
  { header: "Social Protection  Program Affiliation ", key: "socialProtectionProgram", width: 22 },
  { header: "Social Protection: Others", key: "socialProtectionOther", width: 20 },
  { header: "Type of Scheme/ Implementation ", key: "educationScheme", width: 18 },
  { header: "Name of Tie-up Partner", key: "tieUpPartnerName", width: 20 },
  { header: "Staff In- Charge", key: "staffInCharge", width: 16 },
  { header: "Name of Funder     [for Finance Section]", key: "funderName", width: 20 },
  { header: "Location for Reporting", key: "locationForReporting", width: 18 },
  { header: "*REMARKS", key: "remarks", width: 24 },
];